language: cpp
compiler:
- gcc

script:
- ./pushdoc.sh
- ./buildtest.sh
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo add-apt-repository -y ppa:dr-graef/llvm-3.1.precise
- sudo apt-get update -qq
install:
- sudo apt-get install -qq g++-4.7 libclang-dev
- sudo pip install cldoc

env:
  global:
    secure: eyWLuwf/6zIIKECSRZdJM2SW1ai0/FYEiPDtg604OkdmoNZAAUqfFrL1mBzu32gGxZWOHasCMD4DHdtWU7Kf/vIdich4mTAg5nfMux+QPSGNn6xUHYtTGtbj6/baCmAzXUJoIONFbBnj+anOazpaBURpozsMOiHoK5giCHyooLk=
